#!/usr/bin/bash
# setup docker to build and run containers


if [ "$#" -lt 1 ];
then
	yes | cp -vu ./.compose/docker-compose.yaml ../ && yes | cp -vu .env ../
#	docker compose up
elif [[ $1 == "build" ]];
then
	yes | cp -vf ./.compose/docker-compose.yaml ../ && yes | cp -vuf .env ../
#	docker compose up --build
else
	echo "Incorect argument"
	echo "try: ./setupDocker build"
fi

